#!/usr/bin/env bash
# Wire up the two configuration scopes for this session.
#
#   project scope -> /workspace/.claude/        committed with the project, so
#                                               it travels via git pull
#   user scope    -> /home/claude/.claude-user  a private repo bind-mounted from
#                                               the host, so it follows the user
#                                               between machines
#
# Claude Code only knows about one memory directory per project; that one is
# wired to the project scope (claude-sandbox.sh bind-mounts it). The user scope
# is taught to Claude through the generated ~/.claude/CLAUDE.md below, which is
# loaded into every session automatically.
set -euo pipefail

USER_CONFIG=/home/claude/.claude-user
PROJECT_CONFIG=/workspace/.claude
GLOBAL_CLAUDE_MD="${HOME}/.claude/CLAUDE.md"

mkdir -p "${PROJECT_CONFIG}/memory"

if [ -d "${USER_CONFIG}" ]; then
    # Pick up whatever was committed from another machine. Best-effort: no
    # remote, no network or a dirty tree must not stop the session.
    if [ -d "${USER_CONFIG}/.git" ] && [ -n "$(git -C "${USER_CONFIG}" remote)" ]; then
        git -C "${USER_CONFIG}" pull --ff-only --quiet 2>/dev/null \
            || echo "warning: could not pull ${USER_CONFIG}; using the local copy" >&2
    fi

    mkdir -p "${USER_CONFIG}/memory"

    if [ ! -f "${USER_CONFIG}/CLAUDE.md" ]; then
        cat > "${USER_CONFIG}/CLAUDE.md" <<'SCAFFOLD'
# User rules

Rules here apply to every project this user works on. Project-specific rules
belong in the project's own CLAUDE.md instead.
SCAFFOLD
    fi

    if [ ! -f "${USER_CONFIG}/memory/MEMORY.md" ]; then
        : > "${USER_CONFIG}/memory/MEMORY.md"
    fi
fi

# ---------------------------------------------------------------------------
# ~/.claude/CLAUDE.md is loaded into every session, so it is where the scope
# routing has to live. It is regenerated on every container start; the user
# scope's own CLAUDE.md is inlined rather than referenced so it cannot be
# missed.
# ---------------------------------------------------------------------------
{
    cat <<'HEADER'
<!-- Generated by claude-sandbox on container start. Edits here are lost;
     edit /home/claude/.claude-user/CLAUDE.md instead. -->

# Configuration scopes

Rules and memories in this sandbox are split into two scopes. Keeping them
straight is what lets project knowledge travel with the repo and personal
working style travel with the user.

## Project scope — `/workspace/.claude/`

Facts about *this* codebase: architecture decisions, build and test recipes,
gotchas, ongoing work. Committed with the project, so a `git pull` on another
machine brings them along.

- Memories: `/workspace/.claude/memory/` — this is the memory directory named
  in your system prompt, so memories you write the normal way land here.
- Rules: `/workspace/CLAUDE.md` and `/workspace/.claude/settings.json`.
- Machine-local overrides that must NOT be committed:
  `/workspace/.claude/settings.local.json`.

## User scope — `/home/claude/.claude-user/`

Facts about *the user*: who they are, how they want you to work, preferences
that hold no matter which repo is open. A private git repo bind-mounted from
the host, pulled at the start of every session.

- Memories: `/home/claude/.claude-user/memory/`, indexed by
  `/home/claude/.claude-user/memory/MEMORY.md`.
- Rules: `/home/claude/.claude-user/CLAUDE.md` (inlined below).

## Which scope does a memory belong in?

Ask: **would this still be true on a different project?**

- Yes → user scope. `type: user` (who they are) and most `type: feedback`
  (how they want you to work) memories.
- No → project scope. `type: project` memories, and `type: reference` pointers
  to this project's dashboards, tickets or docs.

A `type: feedback` memory that only holds for this repo ("always run
`./actual test` before pushing *here*") is project scope. The same instinct
stated generally ("run the full suite, not one file, before pushing") is user
scope.

When you write to the user scope, commit and push it — run
`claude-user-sync` — or the memory never reaches the user's other machines.
Project-scope memories are committed with the code changes they describe.
HEADER

    if [ -d "${USER_CONFIG}" ]; then
        printf '\n---\n\n'
        cat "${USER_CONFIG}/CLAUDE.md"

        if [ -s "${USER_CONFIG}/memory/MEMORY.md" ]; then
            printf '\n---\n\n# User memory index\n\n'
            printf 'Files listed here live in `%s/memory/`.\n\n' "${USER_CONFIG}"
            cat "${USER_CONFIG}/memory/MEMORY.md"
        fi
    else
        printf '\n---\n\n**No user scope is mounted.** '
        printf 'Set `CS_USER_CONFIG` to a checkout of the user config repo to '
        printf 'enable it; until then, keep user-scope facts out of the '
        printf 'project memory directory.\n'
    fi
} > "${GLOBAL_CLAUDE_MD}"
